### ISSUE TITLE
Feature List

### ISSUE THREAD

**Issue by SiegeTheDay90** [jtabor214/betsy#2]
- [x] Should have 7 MVPs.
  - [x] 3 of those are User Auth, Render, and Production README.
  - [x]  The other 4 are from the [Approved Apps List](https://github.com/appacademy/cohort-resources/blob/master/full_stack_projects/aa_approved_full_stack_projects.md) or your PM will have clarified them with you
 Contains a description sentence of the app
 Includes two to three detailed bullets on functionality and presentation of feature
 At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
 Estimates how long it will take the code each MVP
 Correctly formatted

  - [x] MVPs are listed in an ordered list
  - [x]  Each MVP is broken down into bullet points

**Comment by SiegeTheDay90** [comment]
Stick to these 4 recommended features for now: 
Feature 3: Product Listings
Feature 4: Shopping Cart - CRUD
Feature 5: Comments/Reviews - CRUD
Feature 6: Search

Features 1, 2, and 7 are "Hosted on Render", "User Authentication", and "Production Readme".

**Comment by jtabor214** [comment]
- [ ] Should have 7 MVPs.
    - [ ] 3 of those are User Auth, Render, and Production README.

    - [ ] The other 4 are from the [Approved Apps List](https://github.com/appacademy/cohort-resources/blob/master/full_stack_projects/aa_approved_full_stack_projects.md) or your PM will have clarified them with you
Contains a description sentence of the app
Includes two to three detailed bullets on functionality and presentation of feature
At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
Estimates how long it will take the code each MVP
Correctly formatted

    - [ ] MVPs are listed in an ordered list

     - [ ] Each MVP is broken down into bullet points

**Comment by jtabor214** [comment]
Separated the Posts & Reviews feature into a Products feature, and Reviews feature. Also reorganized the layout of the Feature List, including adding a bonus section for the Likes and Profile features
