### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by SiegeTheDay90** [jtabor214/betsy#5]
- [ ] Frontend routes contains wildcard variables written in `camelCase`
- [ ] Correctly formatted
  - [ ] Routes are displayed with `inline coding text` (backticks)

**Comment by jtabor214** [comment]
Set up some initial frontend routes, but not sure if those are all I need?

**Comment by SiegeTheDay90** [comment]
Don't forget to update with your new routes such as `/search/:query`!
